create table if not exists codes (id int8 generated by default as identity, code varchar(255), device_count int4 not null, duration int4 not null, first_activation_date timestamp, type varchar(255), product_id int8, primary key (id));
create table if not exists license (id int8 generated by default as identity, activation_date timestamp, devise_id int8 not null, ending_date timestamp, code_id int8, primary key (id));
create table if not exists product (id int8 generated by default as identity, is_blocked boolean not null, name varchar(255), primary key (id));
create table if not exists roles (id int4 generated by default as identity, name varchar(255), primary key (id));
create table if not exists users (id int8 generated by default as identity, login varchar(255), password varchar(255), role_id int4, primary key (id));
alter table if exists codes add constraint FKlx7pkbn3qn43evsv5a8cvdpnw foreign key (product_id) references product;
alter table if exists license add constraint FK83h48qb654ei5d7qqh0ru4wd0 foreign key (code_id) references codes;
alter table if exists users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles;