name: Push
on:
  push:
    branches: [ master ]

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew -Dskip.tests build
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: kmisoib
        path: build/libs/*.jar
        retention-days: 5
    
 heroku:
   needs: build
   runs-on: ubuntu-latest
   env:
     DOCKER_REGISTRY: registry.heroku.com
     MAIN_DOCKER_IMAGE_NAME: kmisoibkr
   steps:
  
   - name: Checkout repo
     uses: actions/checkout@v1
   
   - name: Inject slug/short variables
     uses: rlespinasse/github-slug-action@v3.x
  
   - name: Download a single artifact
     uses: actions/download-artifact@v2
     with:
       name: kmisoib
      
   - name: Login to Heroku Container registry
     uses: docker/login-action@v1
     with:
       registry: registry.heroku.com
       Username: f.matorin@mail.ru
       Password: ${{ secrets.HEROKU_API_KEY }}
       
   - name: write_file
     uses: timheuer/base64-to-file@v1.1
     with:
      fileName: 'diplomKeyStore'
      fileDir: './'
      encodedString: ${{ secrets.SERT }
    
   - name: Build and push docker container
     uses: docker/build-push-action@v2
     with:
       context: .
       push: true
       tags: registry.heroku.com/license-diplom/web

   - name: Release
     env:
       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
       run: heroku container:push license-diplom web
     run: heroku container:release -a license-diplom web
